from ExpectedTexts import expected

locator = {
    'add_group_page': {
        'title': '//*[@id="content"]/h1',
        'breadcrumbs': '//*[@id="container"]/div[2]',
        'home_link': '//*[@id="container"]/div[2]/a[1]',
        'authentication_and_authorization_link': '//*[@id="container"]/div[2]/a[2]',
        'groups_link': '//*[@id="container"]/div[2]/a[3]',
        'add_group': '//*[@id="content"]/h1',
        'name': '//*[@id="group_form"]/div/fieldset/div[1]/div/label',
        'input_name_field': '//*[@id="id_name"]',
        'permissions': '//*[@id="group_form"]/div/fieldset/div[2]/div/label',
        'available_permissions_title': '//*[@id="group_form"]/div/fieldset/div[2]/div/div[1]/div/div[1]/h2',
        'input_permission_field': '//*[@id="id_permissions_input"]',
        'available_permissions_tooltip': '//*[@id="group_form"]/div/fieldset/div[2]/div/div[1]/div/div[1]/h2/span',
        'available_permissions_dropdown': '//*[@id="id_permissions_from"]',
        'generic_filtered_permission': '//*[@id="id_permissions_from"]/option',
        'choose_all_permissions_option': '//*[@id="id_permissions_add_all_link"]',
        'choose_all_permissions': '//*[@id="id_permissions_add_all_link"]',
        'help_to_select_multiple_permissions': '//*[@id="group_form"]/div/fieldset/div[2]/div/div[2]',
        'chosen_permissions_title': '//*[@id="group_form"]/div/fieldset/div[2]/div/div[1]/div/div[2]/h2',
        'chosen_permissions_tooltip': '//*[@id="group_form"]/div/fieldset/div[2]/div/div[1]/div/div[2]/h2/span',
        'chosen_permissions_dropdown': '//*[@id="id_permissions_to"]',
        'generic_chosen_permission': '//*[@id="id_permissions_to"]/option',
        'remove_all_permissions_option': '//*[@id="id_permissions_remove_all_link"]',
        'save_and_add_another_button': '//*[@id="group_form"]/div/div/input[2]',
        'save_and_continue_editing_button': '//*[@id="group_form"]/div/div/input[3]',
        'save_button': '//*[@id="group_form"]/div/div/input[1]',
    },
    'groups_page': {
        'breadcrumbs': '//*[@id="container"]/div[2]',
        'home_link': '//*[@id="container"]/div[2]/a[1]',
        'authentication_and_authorization_link': '//*[@id="container"]/div[2]/a[2]',
        'group_x_added_successfully': '//*[@id="container"]/ul/li[@class="success"]',
        'select_group_to_change': '//*[@id="content"]/h1',
        'add_group': '//*[@id="content-main"]/ul/li/a',
        'search_button': '//*[@id="changelist-search"]/div/input[2]',
        'action': '//*[@id="changelist-form"]/div[1]/label',
        'default_option':'//*[@id="changelist-form"]/div[1]/label/select',
        'delete_selected_groups_option': f'//*[@id="changelist-form"]/div[1]/label/select/option[contains(.,"{expected["groups_page"]["delete_selected_groups_option_text"]}")]',
        'delete_selected_groups_option_2': '//select[@name="action"]',
        'go_button': '//*[@id="changelist-form"]/div[1]/button',
        'x_of_y_selected': '//*[@id="changelist-form"]/div[1]/span',
        'select_all_groups': '//*[@id="result_list"]/thead/tr/th[2]/div[1]/span',
        'generic_group_element_checkbox': '//*[@id="result_list"]/tbody/tr[contains(.,"%s")]/td/input[@type="checkbox"]',
        'generic_group_element': '//table[@id="result_list"]/tbody/tr/th/a[contains(.,"%s")]',
        'y_groups': '//*[@id="changelist-form"]/p',
    },
    'confirm_groups_deletions_page': {
        'breadcrumbs': '//*[@id="container"]/div[2]',
        'home': '//*[@id="container"]/div[2]/a[1]',
        'authentication_and_authorization': '//*[@id="container"]/div[2]/a[2]',
        'groups': '//*[@id="container"]/div[2]/a[3]',
        'are_you_sure_headline': '//*[@id="content"]/h1',
        'are_you_sure_question': '//*[@id="content"]/p',
        'summary': '//*[@id="content"]/h2[1]',
        'objects': '//*[@id="content"]/h2[2]',
        'generic_group_element': '//*[@id="content"]/ul[2]/li/a[contains(.,"%s")]',
        'confirm_deletion_button': '//*[@id="content"]/form/div/input[4]',
        'cancel_deletion_button': '//*[@id="content"]/form/div/a',
    }
}